### PR TITLE
Added Feed and PartyCard component with route to get all parties.

### PR DESCRIPTION
**Pull request by elwerro**
# Without this change

# With this change

### CODE REVIEW

**Comment by elwerro** [comment]
Oh no, accidentally pushed and created put request using an old branch(angel_dropdown).

**Comment by meows** [comment]
There are still some merge conflicts!

**Comment by meows** [comment]
There are still some merge conflicts. Did you want to close this PR or r u gonna update?

**Comment by elwerro** [comment]
> 

Yes fixed the merge conficts.

**Review by meows — APPROVED** [review]
nice

**Pull request merged**
